#Faça um programa que leia um número Inteiro qualquer e mostre na tela a sua tabuada.

n = int(input('Digite um número qualquer: '))
print('='*10, 'TABUADA', '='*10)
print('{} * {} = {}'.format(n, 0, n * 0))
print('{} * {} = {}'.format(n, 1, n * 1))
print('{} * {} = {}'.format(n, 2, n * 2))
print('{} * {} = {}'.format(n, 3, n * 3))
print('{} * {} = {}'.format(n, 4, n * 4))
print('{} * {} = {}'.format(n, 5, n * 5))
print('{} * {} = {}'.format(n, 6, n * 6))
print('{} * {} = {}'.format(n, 7, n * 7))
print('{} * {} = {}'.format(n, 8, n * 8))
print('{} * {} = {}'.format(n, 9, n * 9))
print('{} * {} = {}'.format(n, 10, n * 10))
print('='*29)